version: '3'
services:
  komodod:
    tty: true
    restart: always
    image: hbeckeri/komodod:1.0.0
    volumes:
     - ./data:/coin/data
     - ./coin.conf:/root/.komodo/komodo.conf
     - ./coin.conf:/coin/data/komodo.conf
    ports:
       - 7771:7771
