version: '3'
services:
  komodod:
    tty: true
    restart: always
    image: hbeckeri/komodod:latest
    volumes:
     - ./data:/coin/data
     - ./coin.conf:/root/.komodo/komodo.conf
     - ./coin.conf:/coin/data/komodo.conf
    ports:
       - 3000:3000
       - 3001:3001
